from distutils.core import setup
from setuptools import find_packages

setup(
    name="python-flask",
    version="0.0.1",
    description="API with Python and Flask",
    author="Marco Gattello",
    author_email="mgattello@gmail.com",
    url="https://github.com/mgattello/python-flusk",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    package_dir={"": "src"},
    packages= find_packages(where="src"),
    python_requires=">=3.6",
    install_requires = [
        "aniso8601>=9.0.1",
        "attrs>=21.2.0",
        "certifi>=2021.10.8",
        "charset-normalizer>=2.0.7",
        "click>=8.0.3",
        "Flask>=2.0.2",
        "flask-marshmallow>=0.14.0",
        "Flask-SQLAlchemy>=2.5.1",
        "greenlet>=1.1.2",
        "idna>=3.3",
        "iniconfig>=1.1.1",
        "itsdangerous>=2.0.1",
        "Jinja2>=3.0.2",
        "MarkupSafe>=2.0.1",
        "marshmallow>=3.14.0",
        "marshmallow-sqlalchemy>=0.26.1",
        "numpy>=1.21.4",
        "packaging>=21.2",
        "panda>=0.3.1",
        "pandas>=1.3.4",
        "pluggy>=1.0.0",
        "py>=1.10.0",
        "PyMySQL>=1.0.2",
        "pyparsing>=2.4.7",
        "pytest>=6.2.5",
        "python-dateutil>=2.8.2",
        "pytz>=2021.3",
        "requests>=2.26.0",
        "six>=1.16.0",
        "SQLAlchemy>=1.4.26",
        "toml>=0.10.2",
        "urllib3>=1.26.7",
        "Werkzeug>=2.0.2",
    ]
)